### PR TITLE
Add server-side FHIR resources and routes

### PR DESCRIPTION
**Pull request by sjpadgett**
- Patients
 -- http://localhost/openemr-rest/apis/fhir/Patient/30
 -- http://localhost/openemr-rest/apis/fhir/Patient
 -- http://localhost/openemr-rest/apis/fhir/Patient?name=B
- Encounters
 -- http://localhost/openemr-rest/apis/fhir/Encounter/2249
 -- http://localhost/openemr-rest/apis/fhir/Encounter?patient=30
 -- http://localhost/openemr-rest/apis/fhir/Encounter?patient=30&practitioner=1

### CODE REVIEW

**Comment by sjpadgett** [comment]
First, can someone tell me what is our current licence block? Last I knew it was the GNU Affero General Public License 3.
This gives an idea how the FHIR bundle works. I choose container type where both resources and resource references are used. Can bundle say a Patient bundle that includes their encounters, meds, issues and condition e.t.c.. My thought is that we'll be very bundle focused to get the most from a single api call.
Need to start thinking about a capability statement resource defining what resources and searches are available to FHIR clients.
I sure am feeling lonely out here. :)

**Comment by sjpadgett** [comment]
{
  "meta": {
    "lastUpdated": "2018-11-18T19:59:29"
  },
  "resourceType": "Bundle",
  "identifier": "Encounterbundle",
  "type": "collection",
  "total": 3,
  "link": [{
    "relation": "self",
    "url": "http\/\/localhost\/openemr-rest\/apis\/fhir\/Encounter?patient=30"
  }],
  "entry": [{
    "fullUrl": "http\/\/localhost\/openemr-rest\/apis\/fhir\/Encounter\/2247",
    "resource": {
      "id": "2247",
      "resourceType": "Encounter",
      "status": "finished",
      "subject": {
        "reference": "Patient\/30"
      },
      "participant": [{
        "period": {
          "start": "2018-09-26"
        },
        "individual": {
          "reference": "Practitioner\/1"
        }
      }],
      "reason": [{
        "text": ""
      }]
    }
  }, {
    "fullUrl": "http\/\/localhost\/openemr-rest\/apis\/fhir\/Encounter\/9",
    "resource": {
      "id": "9",
      "resourceType": "Encounter",
      "status": "finished",
      "subject": {
        "reference": "Patient\/30"
      },
      "participant": [{
        "period": {
          "start": "2018-05-22"
        },
        "individual": {
          "reference": "Practitioner\/1"
        }
      }],
      "reason": [{
        "text": "Pt here for 3 month follow up and labs. "
      }]
    }
  }, {
    "fullUrl": "http\/\/localhost\/openemr-rest\/apis\/fhir\/Encounter\/5",
    "resource": {
      "id": "5",
      "resourceType": "Encounter",
      "status": "finished",
      "subject": {
        "reference": "Patient\/30"
      },
      "participant": [{
        "period": {
          "start": "2017-04-03"
        },
        "individual": {
          "reference": "Practitioner\/1"
        }
      }],
      "reason": [{
        "text": "Initial Consult for evaluation"
      }]
    }
  }]
}

**Comment by bradymiller** [comment]
speaking of lonely...
https://github.com/openemr/openemr/pull/1980/files

Guessing this license block should be GPL3
(note there are issues with affero license in the cloud world; contact me offline for more info on that)

I am still planning on trying out all this cool stuff in the very near future :)

**Comment by bradymiller** [comment]
btw, isn't there a token api sql table we need to add to the database? I remember seeing it somewhere in the docs previously, but can't find it?

**Comment by sjpadgett** [comment]
yep, here an export for now. I think we're waiting to do any main line additions after master merge.
CREATE TABLE `api_token` (
  `id` bigint(20) NOT NULL,
  `user_id` bigint(20) NOT NULL,
  `token` varchar(256) DEFAULT NULL,
  `expiry` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


ALTER TABLE `api_token`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `api_token`
  MODIFY `id` bigint(20) NOT NULL AUTO_INCREMENT;

**Pull request merged**
